version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_DB: ffmm_vectorcapital_development
      POSTGRES_USER: practicantecomercial
      POSTGRES_PASSWORD: ok

  backend:
    image: 10.0.1.8:5000/ffmm-backend:1.1
    ports:
      - "3005:3001"
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432  
      DB_NAME: ffmm_vectorcapital
      DB_USER: practicantecomercial
      DB_PASSWORD: ok
      DB_USERNAME: practicantecomercial
      EMAIL_USER: practicantecomercial@vectorcapital.cl
      EMAIL_PASSWORD: Vector.2023
      VOULTECH_URL: https://apiwebcbvoultechcertificacion.azurewebsites.net
      VOULTECH_USER: portalfondos
      VOULTECH_PASSWORD: v4rHYG63f9d639G
    volumes:
      - .:/app
    command: ["yarn", "start"]

  frontend_cliente:
    image: 10.0.1.8:5000/ffmm-clients:1.1
    ports:
      - "3004:3002"
    environment:
      VITE_BACKEND_URL: http://10.0.1.8:3005
    volumes:
      - .:/app

  frontend_admin:
    image: 10.0.1.8:5000/ffmm-admin:1.0
    ports:
      - "3006:3003"
    environment:
      VITE_BACKEND_URL: http://10.0.1.8:3005
    volumes:
      - .:/app


