version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_DB: ffmm_vectorcapital_development
      POSTGRES_USER: practicantecomercial
      POSTGRES_PASSWORD: ok

  backend:
    image: ffmm-backend
    ports:
      - "3005:3001"
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432  
      DB_NAME: ffmm_vectorcapital
      DB_USER: practicantecomercial
      DB_PASSWORD: ok
    volumes:
      - .:/app
    command: ["yarn", "start"]

  frontend_cliente:
    image: ffmm-clients
    ports:
      - "3004:3002"
    volumes:
      - .:/app


